---
- hosts: all
  become: true
  tasks:
  - name: install maven
    apt:
      pkg: maven
      state: present
    notify:
    - run update
  - name: install tomcat
    apt:
      pkg: tomcat9
      state: present
  - name: install docker
    apt:
      pkg: docker.io
      state: present
  - name: start docker service
    service:
      name: docker
      state: started
      enabled: true
  - name: deploy springboot application
    command: docker run -it -d -p 8888:8888 --name springboot mayukh656/springboot:1.0
  handlers:
  - name: run update
    apt:
      update_cache: yes
